#!/bin/sh

# ステージエリアに追加されているファイルのうち、
# src/ 以下のファイルのみを対象にする
FILES=$(git diff --cached --name-only --diff-filter=ACM)

if ! echo "$FILES" | grep -q "^src/.*"
then
    exit 0
fi

# 自動生成されたAPIクライアントのファイルのみの変更の場合は、対処外にする
if ! echo "$FILES" | grep -v "^src/api/"
then
    exit 0
fi

echo "testing and Static code analysis now..."
echo "========================================"
storybook_container_state=$(
  cd infra/ && \
  docker compose ps \
    --format json | jq -r '.[] | select(.Name == "infra-storybook-1").State'
)

if [ "$storybook_container_state" != "running" ]; then
  echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
  echo "@ Storybook container is not running, aborting commit"
  echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
  exit 1
fi

# ESLint
(npx eslint src/ --ext .js,.jsx,.ts,.tsx) &
eslint_pid=$!

# Jest
(CI=true make test) &
jest_test_pid=$!

# Storybook
(CI=true make test-storybook) &
storybook_test_pid=$!

wait $eslint_pid
if [ $? -ne 0 ]; then
  echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
  echo "@ ESLint failed, aborting commit"
  echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
  exit 1
fi

wait $jest_test_pid
if [ $? -ne 0 ]; then
  echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
  echo "@ Tests failed, aborting commit"
  echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
  exit 1
fi

wait $storybook_test_pid
if [ $? -ne 0 ]; then
  echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
  echo "@ Storybook tests failed, aborting commit"
  echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
  exit 1
fi

echo "========================================"
