# https://mcr.microsoft.com/en-us/product/devcontainers/typescript-node/tags
FROM mcr.microsoft.com/devcontainers/typescript-node:0-20

RUN curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
RUN echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list

RUN sudo apt-get -y update && sudo apt-get -y install \
    xdg-utils \
    vlt \
    && sudo apt-get clean && sudo rm -rf /var/lib/apt/lists/*
